Job/Job/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Job/jobs/urls.py
from django.urls import path
from .views import *


app_name = "jobs"
urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('create-job/',CreateJobView.as_view(),name="create_job"),
    path('search/',SearchJobView.as_view(),name="search"),
    path('detail/<slug>/<int:pk>/',SingleJobView.as_view(),name="single_job"),
    path('category-detail/<slug>/<int:pk>/', CategoryDetailView.as_view(), name="category_detail"),
]

Job/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('update-profile/<int:pk>/', UserUpdateView.as_view(), name='update_profile'),
    path('employee-profile/<int:pk>/', EmployeeProfileView.as_view(), name='employee_profile'),
    path('employer-jobs/', EmployerPostedJobsView.as_view(), name='employer_jobs'),
]

Job/users/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import gettext_lazy as _
from PIL import Image
from ckeditor.fields import RichTextField
from django.dispatch import receiver


# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('your email is not correct!')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_super', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_super = True')

        return self._create_user(email, password, **extra_fields)


class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=50, blank=False)
    last_name = models.CharField(_('last name'), max_length=50, blank=False)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('is_staff'), default=False)
    is_employee = models.BooleanField(default=False)
    is_employer = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_profile_id(self):
        return self.profile.id


class Profile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, related_name="profile")
    image = models.ImageField(upload_to="media/users", default="media/users/person_1.jpg")
    birth_day = models.DateTimeField(default=None, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True)
    resume = RichTextField(blank=True)
    company = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + " " + self.user.email

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        img = Image.open(self.image)
        if img.height > 200 or img.width > 200:
            new_size = (200, 200)
            img.thumbnail(new_size)
            img.save(self.image.path)


@receiver(models.signals.post_save, sender=Account)
def post_save_user_signal(sender, instance, created, **kwargs):
    if created:
        instance.save()


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=Account)

Job/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Account, Profile


class AccountRegisterForm(UserCreationForm):
    CHOICES = [('is_employee', 'Employee'), ('is_employer', 'Employer')]
    user_types = forms.CharField(label='User Type', widget=forms.RadioSelect(choices=CHOICES))

    class Meta:
        model = Account
        fields = ['email', 'first_name', 'last_name']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

        widgets = {
            'birth_day': forms.DateInput(attrs={'type': 'date'})
        }

Job/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator

from jobs.models import Category, Job
from .forms import AccountRegisterForm, UserUpdateForm

# Create your views here.
from django.views.generic import CreateView, UpdateView, DetailView, ListView

from .models import Profile, Account


class UserRegisterView(SuccessMessageMixin, CreateView):
    template_name = 'users/user-register.html'
    form_class = AccountRegisterForm
    success_url = '/'
    success_message = 'Your user account has been created!!'

    def form_valid(self, form):
        user = form.save(commit=False)
        user_type = form.cleaned_data['user_types']
        if user_type == 'is_employee':
            user.is_employee = True
        elif user_type == 'is_employer':
            user.is_employer = True

        user.save()

        return redirect(self.success_url)


class UserLoginView(LoginView):
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    template_name = 'users/login.html'


@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class UserUpdateView(SuccessMessageMixin, UpdateView):
    model = Profile
    success_message = "You updated your profile!"
    template_name = 'users/update.html'
    form_class = UserUpdateForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(UserUpdateView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect('/')
        return super(UserUpdateView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('users:update_profile', kwargs={'pk': self.object.pk})


class EmployeeProfileView(DetailView):
    template_name = 'users/employee-profile.html'
    model = Account

    def get_context_data(self, **kwargs):
        context = super(EmployeeProfileView, self).get_context_data(**kwargs)
        context['account'] = Account.objects.get(pk=self.kwargs['pk'])
        context['profile'] = Profile.objects.get(user_id=self.kwargs['pk'])
        context['categories'] = Category.objects.all()
        return context


@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class EmployerPostedJobsView(ListView):
    template_name = 'users/employer-posted-jobs.html'
    context_object_name = 'employer_jobs'
    model = Job
    paginate_by = 3

    def get_queryset(self):
        return Job.objects.filter(employer=self.request.user).order_by('-id')

Job/templates/users/employee-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'jobs:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Employee Profile</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate" style="text-align:center">
            <h2 class="mb-3">{{ account.first_name }} {{ account.last_name }}</h2>
              <h5><img src="{{ profile.image.url }}"></h5>
              <h5>Email: {{ account.email }}</h5>
              <h5>Birth Date: {{ profile.birth_day }}</h5>
              <h5>Location: {{ profile.location }}</h5>
            <p>{{ profile.resume|safe }} </p>
            <hr>



          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">
            <div class="sidebar-box">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
                  {% for category in categories %}
                <li><a href="#">{{ category.title }} <span>{{ category.job_count }}</span></a></li>
                  {% endfor %}
              </div>
            </div>



          </div>

        </div>
      </div>
    </section> <!-- .section -->

		{% endblock %}

Job/templates/users/employer-posted-jobs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-xl-10 ftco-animate mb-5 pb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="mb-4 mt-5 pt-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">We have <span class="number" data-number="850000">0</span> great job offers you deserve!</p>
            <h1 class="mb-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Your Dream <br><span>Job is Waiting</span></h1>

						<div class="ftco-search">
							<div class="row">
		            <div class="col-md-12 nav-link-wrap">
			            <div class="nav nav-pills text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
			              <a class="nav-link active mr-md-1" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Find a Job</a>

			              <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Find a Candidate</a>

			            </div>
			          </div>
			          <div class="col-md-12 tab-wrap">

			            <div class="tab-content p-4" id="v-pills-tabContent">

			              <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-nextgen-tab">
			              	<form action="{% url 'jobs:search'%}" class="search-job" method="get">
			              		<div class="row">
			              			<div class="col-md">
			              				<div class="form-group">
				              				<div class="form-field">
				              					<div class="icon"><span class="icon-briefcase"></span></div>
								                <input type="text" name="job_title" class="form-control" placeholder="eg. Garphic. Web Developer">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="select-wrap">
						                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
						                      <select name="job_type" id="" class="form-control"> //id=""

                                                  <option value="full_time">Full Time</option>
						                        <option value="part_time">Part Time</option>
						                        <option value="freelance">Freelance</option>
						                        <option value="internship">Internship</option>
						                        <option value="temporary">Temporary</option>
						                      </select>
						                    </div>
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="icon"><span class="icon-map-marker"></span></div>
								                <input type="text" name="job_location" class="form-control" placeholder="Location">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
								                <input type="submit" value="Search" class="form-control btn btn-primary">
								              </div>
							              </div>
			              			</div>
			              		</div>
			              	</form>
			              </div>

			              <div class="tab-pane fade" id="v-pills-2" role="tabpanel" aria-labelledby="v-pills-performance-tab">
			              	<form action="#" class="search-job">
			              		<div class="row">
			              			<div class="col-md">
			              				<div class="form-group">
				              				<div class="form-field">
				              					<div class="icon"><span class="icon-user"></span></div>
								                <input type="text" class="form-control" placeholder="eg. Adam Scott">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="select-wrap">
						                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
						                      <select name="" id="" class="form-control">
						                      	<option value="">Category</option>
						                      	<option value="">Full Time</option>
						                        <option value="">Part Time</option>
						                        <option value="">Freelance</option>
						                        <option value="">Internship</option>
						                        <option value="">Temporary</option>
						                      </select>
						                    </div>
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="icon"><span class="icon-map-marker"></span></div>
								                <input type="text" class="form-control" placeholder="Location">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
								                <input type="submit" value="Search" class="form-control btn btn-primary">
								              </div>
							              </div>
			              			</div>
			              		</div>
			              	</form>
			              </div>
			            </div>
			          </div>
			        </div>
		        </div>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section services-section bg-light">
      <div class="container">
        <div class="row d-flex">
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-resume"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Search Millions of Jobs</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-collaboration"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Easy To Manage Jobs</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-promotions"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Top Careers</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-employee"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Search Expert Candidates</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


		<section class="ftco-section bg-light">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section text-center ftco-animate">
          	<span class="subheading">Your Added Jobs</span>
            <h2 class="mb-4"><span>Recently</span> Added</h2>
          </div>
        </div>

         <div class="row">
             {% if user.is_employer and employer_jobs %}
             {% for job in employer_jobs %}
             <div class="col-md-12 ftco-animate">
                            <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">

                              <div class="mb-4 mb-md-0 mr-5">
                               <div class="job-post-item-header d-flex align-items-center">
                                 <h2 class="mr-3 text-black h4">{{job.title}}</h2>
                                 <div class="badge-wrap">
                                     {% if job.job_type == 'full_time' %}
                                        <span class="bg-warning text-white badge py-2 px-3">Full Time</span>
                                     {% elif job.job_type == 'part_time' %}
                                        <span class="bg-info text-white badge py-2 px-3">Part Time</span>
                                     {% elif job.job_type == 'freelance' %}
                                        <span class="bg-secondary text-white badge py-2 px-3">Freelance</span>
                                     {% elif job.job_type == 'internship' %}
                                        <span class="bg-primary text-white badge py-2 px-3">Internship</span>
                                     {% elif job.job_type == 'temporary' %}
                                        <span class="bg-danger text-white badge py-2 px-3">Temporary</span>
                                     {% endif %}
                                 </div>
                               </div>
                               <div class="job-post-item-body d-block d-md-flex">
                                 <div class="mr-3"><span class="icon-layers"></span> <a href="#">{{job.company}}</a></div>
                                 <div><span class="icon-my_location"></span> <span>{{job.location}}</span></div>
                               </div>
                              </div>

                              <div class="ml-auto d-flex">
                                <a href="{% url 'jobs:single_job' job.slug job.pk %}" class="btn btn-primary py-2 mr-1">Apply Job</a>
                                <a href="#" class="btn btn-danger rounded-circle btn-favorite d-flex align-items-center">
                                <span class="icon-heart"></span>
                                </a>
                                </div>

                            </div>
              </div> <!-- end -->

             {% endfor %}
                    {% else %}
                          <div class="col-md-12 ftco-animate">
                            <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">

                              <div class="mb-4 mb-md-0 mr-5">
                               <div class="job-post-item-header d-flex align-items-center">
                                 <h2 class="mr-3 text-black h4">You don't have a posted job yet</h2>

                            </div>
              </div> <!-- end -->
                </div>
          </div>
                     {% endif %}

                   {% if user.is_employee %}
              <div class="col-md-12 ftco-animate">
                            <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">

                              <div class="mb-4 mb-md-0 mr-5">
                               <div class="job-post-item-header d-flex align-items-center">
                                 <h2 class="mr-3 text-black h4"> You are not an employer </h2>

                            </div>
              </div> <!-- end -->
                </div>
          </div>
                    {% endif %}

         <div class="row mt-5">
         {% if is_paginated %}
          <div class="col text-center">
            <div class="block-27">
              <ul>
                  {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>
                  {% else %}
                <li class="disabled"><span>&lt;</span></li>
                  {% endif %}
                  {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                <li class="active"><span>{{ i }}</span></li>
                  {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">></a></li>
                  {% else %}
                <li class="disabled"><span> &gt;</span></li>
                  {% endif %}
              </ul>
            </div>
          </div>
          {% endif %}
        </div>
			</div>
          </div>
		</section>

    {% endblock %}

Job/templates/users/login.html
    {% extends 'base.html' %}
    {%  load static %}

    {% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Login</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Login</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">

              {% if not user.is_authenticated %}

              <form action="#" class="p-5 bg-white" method="post">
                  {% csrf_token %}

                  {% if form.errors %}
                  <div class="alert alert-danger alert-dismissible" role="alert">
                    <div id="form_errors">
                        {% for key,value in form.errors.items %}
                        <span>
                            {{ key }}:{{ value }}
                        </span>
                        {% endfor %}
                    </div>
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="close">
                          <span aria-hidden="turn">&times</span>
                      </button>
                  </div>
                  {% endif %}

                  {% for field in form.visible_fields %}
                <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for= "fullname">{{ field.label }}</label>
                  <input type="{{ field.field.widget.input_type }}" id="fullname" class="form-control" placeholder="{{ field.label }}" name="{{ field.html_name }}">
                </div>
              </div>
                  {% endfor %}

                  <div class="row form-group">
                    <div class="col-md-12">
                      <input type="submit" value="Login" class="btn btn-primary  py-2 px-5">
                    </div>
                  </div>
              </form>

              {% else %}
              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for= "fullname" style="color:green;">You Already Logged in</label>
                </div>
              </div>
              {% endif %}

          </div>


        </div>
      </div>
    </div>

    {% endblock %}

Job/templates/users/user-register.html
    {% extends 'base.html' %}
    {%  load static %}

    {% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>User Register</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Registration Form</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">
              <form action="#" class="p-5 bg-white" method="post">
                  {% csrf_token %}

                  {% if form.errors %}
                  <div class="alert alert-danger alert-dismissible" role="alert">
                    <div id="form_errors">
                        {% for key,value in form.errors.items %}
                        <span>
                            {{ key }}:{{ value }}
                        </span>
                        {% endfor %}
                    </div>
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="close">
                          <span aria-hidden="turn">&times</span>
                      </button>
                  </div>
                  {% endif %}

                  {% for field in form.visible_fields|slice:"5" %}

                <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for= "fullname">{{ field.label }}</label>
                  <input type="{{ field.field.widget.input_type }}" id="fullname" class="form-control" placeholder="{{ field.label }}" name="{{ field.html_name }}">
                </div>
              </div>

                  {% endfor %}

                <div class="row form-group">
                <div class="col-md-12"><h3>User Type</h3></div>
                <div class="col-md-12 mb-3 mb-md-0">
                  <label for="option-job-type-1">
                    {{ form.user_types }}
                  </label>
                </div>
                </div>

                  <div class="row form-group">
                    <div class="col-md-12">
                      <input type="submit" value="Register" class="btn btn-primary  py-2 px-5">
                    </div>
                  </div>

              </form>
          </div>
        </div>
      </div>
    </div>

    {% endblock %}