Job/Job/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Job/jobs/urls.py
from django.urls import path
from .views import *


app_name = "jobs"
urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('create-job/',CreateJobView.as_view(),name="create_job"),
    path('search/',SearchJobView.as_view(),name="search"),
    path('detail/<slug>/<int:pk>/',SingleJobView.as_view(),name="single_job"),
    path('category-detail/<slug>/<int:pk>/', CategoryDetailView.as_view(), name="category_detail"),
]

Job/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('update-profile/<int:pk>/', UserUpdateView.as_view(), name='update_profile'),
    path('employee-profile/<int:pk>/', EmployeeProfileView.as_view(), name='employee_profile'),
    path('employer-jobs/', EmployerPostedJobsView.as_view(), name='employer_jobs'),
]

Job/jobs/models.py
from django.db import models
from django.template.defaultfilters import slugify
# Create your models here.
from Job import settings
from ckeditor.fields import RichTextField


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(default=None, editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def job_count(self):
        return self.jobs.all().count()


class Job(models.Model):
    title = models.CharField(max_length=300)
    company = models.CharField(max_length=300)
    CHOICES = (
        ('full_time', 'Full Time'),  # (key,value)
        ('part_time', 'Part Time'),
        ('freelance', 'Freelance'),
        ('internship', 'Internship'),
        ('temporary', 'Temporary'),
    )

    job_type = models.CharField(max_length=20, blank=False, default=None, choices=CHOICES)
    location = models.CharField(max_length=200, blank=False, default=None)
    description = RichTextField(blank=False, default=None)
    publishing_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(default=None, editable=False)
    employer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    employee = models.ManyToManyField(settings.AUTH_USER_MODEL, default=None, blank=True, related_name="job_employee")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="jobs", default=1)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-id',)

Job/jobs/forms.py
from django import forms
from .models import *


class CreateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'company', 'location', 'job_type', 'category', 'description']
        widgets = {'job_type': forms.RadioSelect}


class ApplyJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = []

Job/jobs/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView
from .forms import *
from .models import Job, Category


class HomeView(ListView):
    template_name = 'jobs/index.html'
    context_object_name = 'jobs'
    model = Job
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


@method_decorator(login_required(login_url='/'), name='dispatch')
class CreateJobView(SuccessMessageMixin, CreateView):
    model = Job
    template_name = 'jobs/create-jobs.html'
    form_class = CreateJobForm
    success_url = '/'
    success_message = "Job has been posted!"

    def form_valid(self, form):
        job = form.save(commit=False)
        job.employer = self.request.user
        job.save()
        return super(CreateJobView, self).form_valid(form)


class SingleJobView(SuccessMessageMixin, UpdateView):
    template_name = 'jobs/single.html'
    model = Job
    context_object_name = 'job'
    form_class = ApplyJobForm
    success_message = "You applied this job!"

    def get_context_data(self, **kwargs):
        context = super(SingleJobView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['employee_applied'] = Job.objects.get(pk=self.kwargs['pk']).employee.all().filter(id=self.request.user.id)
        try:
            context['applied_employees'] = Job.objects.get(pk=self.kwargs['pk'], employer_id=self.request.user.id).employee.all()
            context['employer_id'] = Job.objects.get(pk=self.kwargs['pk']).employer_id
        except:
            pass
        return context

    def form_valid(self, form):
        employee = self.request.user
        form.instance.employee.add(employee)
        form.save()
        return super(SingleJobView, self).form_valid(form)

    def get_success_url(self):
        return reverse('jobs:single_job', kwargs={'slug': self.object.slug, "pk": self.object.pk})


class CategoryDetailView(ListView):
    model = Job
    template_name = 'jobs/category-detail.html'
    context_object_name = 'jobs'
    paginate_by = 2

    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return Job.objects.filter(category=self.category)

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        context['categories'] = Category.objects.all()
        context['category'] = self.category
        return context


class SearchJobView(ListView):
    model = Job
    template_name = 'jobs/search.html'
    paginate_by = 2
    context_object_name = 'jobs'

    def get_queryset(self):
        q1 = self.request.GET.get("job_title")
        q2 = self.request.GET.get("job_type")
        q3 = self.request.GET.get("job_location")

        if q1 or q2 or q3:
            return Job.objects.filter(Q(title__icontains=q1) |
                                      Q(description__icontains=q1),
                                      job_type=q2,
                                      location__icontains=q3).order_by('-id')
        return Job.objects.all().order_by('-id')

    def get_context_data(self, *args, **kwargs):
        context = super(SearchJobView, self).get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()

        return context

Job/templates/jobs/create-jobs.html
    {% extends 'base.html' %}
    {%  load static %}

    {% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Add Job</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Add Job Form</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">
               {% if user.is_employer %}
              <form action="#" class="p-5 bg-white" method="post">
                  {% csrf_token %}

                  {% if form.errors %}
                  <div class="alert alert-danger alert-dismissible" role="alert">
                    <div id="form_errors">
                        {% for key,value in form.errors.items %}
                        <span>
                            {{ key }}:{{ value }}
                        </span>
                        {% endfor %}
                    </div>
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="close">
                          <span aria-hidden="turn">&times</span>
                      </button>
                  </div>
                  {% endif %}

                  {% for field in form.visible_fields|slice:"3" %}

                <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for= "fullname">{{ field.label }}</label>
                  <input type="{{ field.field.widget.input_type }}" id="fullname" class="form-control" placeholder="{{ field.label }}" name="{{ field.html_name }}">
                </div>
              </div>

                  {% endfor %}

                <div class="row form-group">
                <div class="col-md-12"><h3>Job Type</h3></div>
                <div class="col-md-12 mb-3 mb-md-0">
                  <label for="option-job-type-1">
                    {{ form.job_type }}
                  </label>
                </div>
                </div>

                   <div class="row form-group">
                <div class="col-md-12"><h3>Categories</h3></div>
                <div class="col-md-12 mb-3 mb-md-0">
                  <label for="option-job-type-1">
                    {{ form.category }}
                  </label>
                </div>
                </div>

                   <div class="row form-group">
                <div class="col-md-12"><h3>Description</h3></div>
                       {{ form.media }}
                       {{ form.description }}
                </div>

                  <div class="row form-group">
                    <div class="col-md-12">
                      <input type="submit" value="Post" class="btn btn-primary  py-2 px-5">
                    </div>
                  </div>

              </form>
              {% else %}
              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label for="option-job-type-1">
                    You Are Not An Employer
                  </label>
                </div>
                </div>
              {% endif %}
          </div>

        </div>
      </div>
    </div>

    {% endblock %}

Job/templates/jobs/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-xl-10 ftco-animate mb-5 pb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="mb-4 mt-5 pt-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">We have great job offers you deserve!</p>
            <h1 class="mb-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Your Dream <br><span>Job is Waiting</span></h1>

						<div class="ftco-search">
							<div class="row">
		            <div class="col-md-12 nav-link-wrap">
			            <div class="nav nav-pills text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
			              <a class="nav-link active mr-md-1" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Find a Job</a>

			              <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Find a Candidate</a>

			            </div>
			          </div>
			          <div class="col-md-12 tab-wrap">

			            <div class="tab-content p-4" id="v-pills-tabContent">

			              <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-nextgen-tab">
			              	<form action="{% url 'jobs:search'%}" class="search-job" method="get">
			              		<div class="row">
			              			<div class="col-md">
			              				<div class="form-group">
				              				<div class="form-field">
				              					<div class="icon"><span class="icon-briefcase"></span></div>
								                <input type="text" name="job_title" class="form-control" placeholder="eg. Garphic. Web Developer">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="select-wrap">
						                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
						                      <select name="job_type" id="" class="form-control"> //id=""

                                                  <option value="full_time">Full Time</option>
						                        <option value="part_time">Part Time</option>
						                        <option value="freelance">Freelance</option>
						                        <option value="internship">Internship</option>
						                        <option value="temporary">Temporary</option>
						                      </select>
						                    </div>
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="icon"><span class="icon-map-marker"></span></div>
								                <input type="text" name="job_location" class="form-control" placeholder="Location">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
								                <input type="submit" value="Search" class="form-control btn btn-primary">
								              </div>
							              </div>
			              			</div>
			              		</div>
			              	</form>
			              </div>

			              <div class="tab-pane fade" id="v-pills-2" role="tabpanel" aria-labelledby="v-pills-performance-tab">
			              	<form action="#" class="search-job">
			              		<div class="row">
			              			<div class="col-md">
			              				<div class="form-group">
				              				<div class="form-field">
				              					<div class="icon"><span class="icon-user"></span></div>
								                <input type="text" class="form-control" placeholder="eg. Adam Scott">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="select-wrap">
						                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
						                      <select name="" id="" class="form-control">
						                      	<option value="">Category</option>
						                      	<option value="">Full Time</option>
						                        <option value="">Part Time</option>
						                        <option value="">Freelance</option>
						                        <option value="">Internship</option>
						                        <option value="">Temporary</option>
						                      </select>
						                    </div>
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
				              					<div class="icon"><span class="icon-map-marker"></span></div>
								                <input type="text" class="form-control" placeholder="Location">
								              </div>
							              </div>
			              			</div>
			              			<div class="col-md">
			              				<div class="form-group">
			              					<div class="form-field">
								                <input type="submit" value="Search" class="form-control btn btn-primary">
								              </div>
							              </div>
			              			</div>
			              		</div>
			              	</form>
			              </div>
			            </div>
			          </div>
			        </div>
		        </div>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section services-section bg-light">
      <div class="container">
        <div class="row d-flex">
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-resume"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Search Millions of Jobs</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-collaboration"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Easy To Manage Jobs</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-promotions"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Top Careers</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
          <div class="col-md-3 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon"><span class="flaticon-employee"></span></div>
              <div class="media-body">
                <h3 class="heading mb-3">Search Expert Candidates</h3>
                <p>A small river named Duden flows by their place and supplies.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-counter">
    	<div class="container">
    		<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section text-center ftco-animate">
          	<span class="subheading">Categories work waiting for you</span>
            <h2 class="mb-4"><span>Current</span> Job Posts</h2>
          </div>
        </div>
        <div class="row">
            {% for category in categories %}
        	<div class="col-md-3 ftco-animate">
        		<ul class="category">
        			<li><a href="{% url 'jobs:category_detail' category.slug category.pk %}">{{ category.title }} <span class="number" data-number="{{ category.job_count}}">0</span></a></li>
        		</ul>
        	</div>
            {% endfor %}
        </div>
    	</div>
    </section>

		<section class="ftco-section bg-light">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section text-center ftco-animate">
          	<span class="subheading">Recently Added Jobs</span>
            <h2 class="mb-4"><span>Recent</span> Jobs</h2>
          </div>
        </div>

         <div class="row">
             {% for job in jobs %}
             <div class="col-md-12 ftco-animate">
                            <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">

                              <div class="mb-4 mb-md-0 mr-5">
                               <div class="job-post-item-header d-flex align-items-center">
                                 <h2 class="mr-3 text-black h4">{{job.title}}</h2>
                                 <div class="badge-wrap">
                                     {% if job.job_type == 'full_time' %}
                                        <span class="bg-warning text-white badge py-2 px-3">Full Time</span>
                                     {% elif job.job_type == 'part_time' %}
                                        <span class="bg-info text-white badge py-2 px-3">Part Time</span>
                                     {% elif job.job_type == 'freelance' %}
                                        <span class="bg-secondary text-white badge py-2 px-3">Freelance</span>
                                     {% elif job.job_type == 'internship' %}
                                        <span class="bg-primary text-white badge py-2 px-3">Internship</span>
                                     {% elif job.job_type == 'temporary' %}
                                        <span class="bg-danger text-white badge py-2 px-3">Temporary</span>
                                     {% endif %}
                                 </div>
                               </div>
                               <div class="job-post-item-body d-block d-md-flex">
                                 <div class="mr-3"><span class="icon-layers"></span> <a href="#">{{job.company}}</a></div>
                                 <div><span class="icon-my_location"></span> <span>{{job.location}}</span></div>
                               </div>
                              </div>

                              <div class="ml-auto d-flex">
                                <a href="{% url 'jobs:single_job' job.slug job.pk %}" class="btn btn-primary py-2 mr-1">Apply Job</a>
                                <a href="#" class="btn btn-danger rounded-circle btn-favorite d-flex align-items-center">
                                <span class="icon-heart"></span>
                                </a>
                                </div>

                            </div>
              </div> <!-- end -->
             {% endfor %}
         </div>
         <div class="row mt-5">
         {% if is_paginated %}
          <div class="col text-center">
            <div class="block-27">
              <ul>
                  {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>
                  {% else %}
                <li class="disabled"><span>&lt;</span></li>
                  {% endif %}
                  {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                <li class="active"><span>{{ i }}</span></li>
                  {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">></a></li>
                  {% else %}
                <li class="disabled"><span> &gt;</span></li>
                  {% endif %}
              </ul>
            </div>
          </div>
          {% endif %}
        </div>
			</div>
		</section>







    {% endblock %}

Job/templates/jobs/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-3"><a href="blog.html">Job Detail <i class="ion-ios-arrow-forward"></i></a></span> </p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Job Detail</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">
            <h2 class="mb-3">{{ job.title }}</h2>
            <p>{{ job.description|safe }} </p>
            <hr>
            <form method="post">
              {% csrf_token %}
            {% if user.is_employee %}

              <div class="ml-auto d-flex">
                {% if employee_applied %}
            <input type="submit" value="Apply" class="btn btn-primary py-2 mr-1" disabled title="You Already applied">
              {% else %}
             <input type="submit" value="Apply" class="btn btn-primary py-2 mr-1">
              <a href="#" class="btn btn-danger rounded-circle btn-favorite d-flex align-items-center">
                <span class="icon-heart"></span>
              </a>
                {% endif %}
                </div>
             {% endif %}
            </form>

            {% if user.is_employer and user.id == employer_id %}
            {% if applied_employees %}
            <div class="list-group">
            <button type="button" class="list-group-item list-group-item-action active" style="text-align:center">
                Applied Candidates
            </button>

            {% for employee in applied_employees %}
            <a href="{% url 'users:employee_profile' pk=employee.pk %}" class="list-group-item list-group-item-action">
              {{ employee.first_name }} {{ employee.last_name}}
            </a>
            {% endfor %}
          </div>

            {% else %}
           <div class="list-group">
            <button type="button" class="list-group-item list-group-item-action active" style="text-align:center">
               No Applied Candidates
            </button>
          </div>
          {% endif %}
          {% endif %}

          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">
            <div class="sidebar-box">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
                  {% for category in categories %}
                <li><a href="#">{{ category.title }} <span>{{ category.job_count }}</span></a></li>
                  {% endfor %}
              </div>
            </div>



          </div>

        </div>
      </div>
    </section> <!-- .section -->

		{% endblock %}